### ISSUE TITLE
Installation Tutorial in the Readme Needs an Update

### ISSUE THREAD

**Issue by 101arg101** [serprex/openEtG#32]
When following the instructions on OS X (and probably Windows too) I'm getting an error when loading up the homepage. `:13602/etgify.js:250 Uncaught TypeError: Card is not a constructor`

**Comment by serprex** [comment]
Looks like an issue in Cards.js not having `require("./Card")` but I'm not sure why that bug isn't occuring on the live site. Will look into when I get home

**Comment by serprex** [comment]
I said I'd get to this but instead I don't know I'm experiencing time gone wrong. Tick

**Comment by serprex** [comment]
[Fixed.](https://github.com/serprex/openEtG/commit/ddc94661d3c151c4d030d45aadb754d12690d2e1) Unfortuantely the most stable build method is to use https://ninja-build.org since that's what I use. Thanks for the report

**Comment by 101arg101** [comment]
Yeah, it's fixed. I've been out of touch for the past few days.
