### ISSUE TITLE
Request: Contribution guide + Roadmap

### ISSUE THREAD

**Issue by diggoran** [serprex/openEtG#48]
I would like to contribute to this project, but the workitems are unclear. Please set up the Projects tab in GitHub, and let's work together to plot a roadmap for the future.

For instance, I would like to make a project board of workitems/bugs that are required in order to build a "classic mode" where the game is as close to the current state of Zanz's work as possible.

With clearly defined workitems, short term contributors would have an easier time finding a small job to do.

**Comment by ludamad** [comment]
Hi @diggoran, there currently is a vanilla mode, although I can't speak to how complete. What is your interest in openEtG being closer to classic, if I may ask?

**Comment by serprex** [comment]
There's a branch trying at that https://github.com/serprex/openEtG/tree/original

oetg-v got axed after it was dragging behind with too much technical debt

My progress in this stalled out as winter depression settled in

**Comment by serprex** [comment]
@diggoran there's now a Legacy mode. https://etg.dek.im/forum/index.php?topic=992.msg5038#msg5038 lists small issues
