### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by elysiumplain** [serprex/openEtG#54]
Consideration for migrating from `node-canvas` over to `skia-canvas` https://www.npmjs.com/package/@napi-rs/canvas.

**Comment by elysiumplain** [comment]
Currently there is no arm64 architecture support for node-canvas.

However I found a supplemental package dependency that enables local build: build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

**Comment by serprex** [comment]
I'm confused, we don't use canvas, we did long ago, but since then server is Rust & we generate svg files for `/deck/` & `/card/`

Same for on the clientside, we used to render to canvas, but now it's all DOM
